### ISSUE TITLE
The link to the demo is dead! 

### ISSUE THREAD

**Issue by manthrax** [sneha-belkhale/vertex-texture-cache#1]
The link to the demo in the README/landing page is dead! 

I think it's supposed to link to here? https://codercat.tk/vertex-cache/

Cool project! :D

**Comment by sneha-belkhale** [comment]
hey thanks @manthrax ! strange, I just opened it in my browser.. maybe try again? You may have tried opening it while I was updating the website..

**Comment by sneha-belkhale** [comment]
oh I see what you mean now. yes we changed domains, thanks!
